apiVersion: v1
kind: ConfigMap
metadata:
  name: house-price-api-config
  namespace: ml-system
data:
  MODEL_NAME: "linear-regression-house-price"
  MLFLOW_TRACKING_URI: "file:./mlflow/mlruns"
  LOG_LEVEL: "INFO"
  API_HOST: "0.0.0.0"
  API_PORT: "8000"

