apiVersion: v1
kind: Service
metadata:
  name: house-price-api-service
  namespace: ml-system
  labels:
    app: house-price-api
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
    nodePort: 30080
  selector:
    app: house-price-api

